var userIdArray = [
    "152993148",
    "776351026",
    "459886321"
    ];
    
var doctorSchedule = [
    {
        "specialityId":"001",
        "specialityName":"Терапевт",
        "weekSchedule":[
            {
                "dayOfWeek":"понедельник",
                "startTime":"09:00",
                "endTime":"14:00"
            },
            {
                "dayOfWeek":"вторник",
                "startTime":"12:00",
                "endTime":"18:00"
            },
            {
                "dayOfWeek":"среда",
                "startTime":"12:00",
                "endTime":"18:00"
            },
            {
                "dayOfWeek":"пятница",
                "startTime":"08:00",
                "endTime":"15:00"
            }]
    },
    {
        "specialityId":"002",
        "specialityName":"Офтальмолог",
        "weekSchedule":[
            {
                "dayOfWeek":"понедельник",
                "startTime":"10:00",
                "endTime":"17:00"
            },
            {
                "dayOfWeek":"среда",
                "startTime":"12:00",
                "endTime":"19:00"
            },
            {
                "dayOfWeek":"пятница",
                "startTime":"10:00",
                "endTime":"15:30"
            }]
    },
    {
        "specialityId":"003",
        "specialityName":"Стоматолог",
        "weekSchedule":[
            {
                "dayOfWeek":"вторник",
                "startTime":"08:30",
                "endTime":"16:45"
            },
            {
                "dayOfWeek":"четверг",
                "startTime":"08:00",
                "endTime":"14:15"
            }]
    }];
